### PR TITLE
Fix negative maxBarWidth

### LINKED ISSUE #69: `createBar` invalid array length exception due to negative maxBarWidth
Reproduced in a < 250px width split. `maxBarWidth` was `-4`.

### PR DESCRIPTION
**Pull request by adrianlee44**
Fixes #69

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -75,12 +75,10 @@ module.exports = function (grunt, cb) {
 		}, 0);
 
 		var maxColumns = process.stdout.columns || 80;
-		var maxBarWidth;
+		var maxBarWidth = maxColumns - (longestTaskName + 20);
 
-		if (longestTaskName > maxColumns / 2) {
+		if (maxBarWidth <= 0 || longestTaskName > maxColumns / 2) {
```
Comment (dasilvacontin) [inline index.js]: `maxBarWidth` will end up being negative if `maxColumns` is smaller than 20.

Comment (adrianlee44) [inline index.js]: Updated the changes to default maxBarWidth to 0 if it's negative.

**Comment by adrianlee44** [comment]
This should fix the issue. Will merge this PR soon.
